export const events = [
  {
    id: 1,
    artist: "Container Enthusiasm",
    name: "Talk Docker to Me Tour",
    date: new Date("2021-10-01T19:00:00"),
    price: 49.99,
    imgUrl: "logos/Container-Enthusiasm-TalkDocker-To-Me.png",
  },
  {
    id: 2,
    artist: "Digital Cowboys",
    name: "Binary Bovine Tour",
    date: new Date("2021-11-01T19:30:00"),
    price: 59.99,
    imgUrl: "logos/DigitalCowboys_BinaryBovine.png",
  },
  {
    id: 3,
    artist: "Git Outta My Hub",
    name: "Code Empire Tour",
    date: new Date("2021-12-01T20:00:00"),
    price: 39.99,
    imgUrl: "logos/GitOuttaMyHub-CodeEmpire.png",
  },
  {
    id: 4,
    artist: "Network Firewall Squad",
    name: "For Those About to Block Tour",
    date: new Date("2022-03-08T20:45:00"),
    price: 69.99,
    imgUrl:
      "logos/Network-Firewall-Squad---For-Those-About-to-Block,-We-Salute-You.png",
  },
  {
    id: 5,
    artist: "AI Innovators",
    name: "Code of the Future Tour",
    date: new Date("2022-05-15T18:30:00"),
    price: 55.0,
    imgUrl: "logos/concert.png",
  },
  {
    id: 6,
    artist: "Crypto Wizards",
    name: "Blockchain Revolution Tour",
    date: new Date("2022-07-10T19:15:00"),
    price: 65.0,
    imgUrl: "logos/concert2.png",
  },
  {
    id: 7,
    artist: "Cloud Architects",
    name: "Skybound Tour",
    date: new Date("2022-08-20T20:00:00"),
    price: 49.99,
    imgUrl: "logos/concert3.png",
  },
  {
    id: 8,
    artist: "Data Slingers",
    name: "Byte Party Tour",
    date: new Date("2022-09-15T19:45:00"),
    price: 59.99,
    imgUrl: "logos/concert4.png",
  },
  {
    id: 9,
    artist: "Virtual Reality Ensemble",
    name: "Virtual Worlds Tour",
    date: new Date("2022-10-05T20:30:00"),
    price: 69.99,
    imgUrl: "logos/concert5.png",
  },
  {
    id: 10,
    artist: "Cyberpunk Collective",
    name: "Neon Network Tour",
    date: new Date("2022-11-02T21:00:00"),
    price: 79.99,
    imgUrl: "logos/concert6.png",
  },
];
